# Generated by Django 3.0.5 on 2020-04-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200409_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='url',
            new_name='slug',
        ),
    ]
