# Generated by Django 3.0.5 on 2020-04-13 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20200410_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshot',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie', verbose_name='Фильм'),
        ),
    ]
