# Generated by Django 3.0.5 on 2020-04-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20200429_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviestar',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
    ]
