# Generated by Django 3.0.5 on 2020-05-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20200429_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='directorts',
            new_name='directors',
        ),
    ]
