# Generated by Django 3.0.5 on 2020-05-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20200503_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='film_actor', to='movie.Actor', verbose_name='Актеры'),
        ),
    ]
